Enterprise scope
myoung34/docker-github-actions-runner pull request #111
Opened 2021-05-14 18:27 UTC by jakubstefan

Resolves #45, related to #95.

Adds the possibility to register the runner enterprise-wide. Also, as having now multiple scopes, I considered organising a bit the selection of the scope.

Tested in Enterprise environment.

2021-05-27 09:55 UTC, retzero commented
It also works in our GitHub Ent. Thank you for the changes!

2021-05-28 10:03 UTC, jakubstefan commented
@myoung34 How should we proceed with this? Do you need any more information to support the changes?

2021-05-28 11:11 UTC, myoung34 commented
Sorry, haven't had a chance to review. I'm out this weekend but will review it Monday

2021-05-28 14:03 UTC, jakubstefan commented
No worries. Have a nice weekend.

2021-05-31 01:28 UTC, myoung34 requested changes

2021-05-31 01:28 UTC, myoung34 commented on entrypoint.sh
> -if [[ ${ORG_RUNNER} == "true" ]]; then
For now we should find a way to make it work as-is (with ORG_RUNNER) and as new (RUNNER_SCOPE )

There are quite a few users of this and I'd like to throw some deprecation warnings + a timeline before making a hard change.

2021-05-31 01:28 UTC, myoung34 commented on entrypoint.sh
> +  "org")
for string based we should make it case insensitive and allow shortening for things like org|organization

2021-05-31 01:28 UTC, myoung34 commented on token.sh
> +  [[ -z ${REPO_URL} ]] && ( echo "REPO_URL required for repo runners"; exit 1 )
this already exists in `entrypoint.sh` and shouldnt be a concern in both places (keep it DRY)

2021-05-31 01:28 UTC, myoung34 commented on token.sh
> +case ${RUNNER_SCOPE} in
id like to see if theres a way to shorten the next bit, it seems repetitive from `entrypoint.sh`

2021-06-01 09:39 UTC, jakubstefan commented
I have done some changes to be more flexible with the `RUNNER_SCOPE` value. I have done some code cleaning as well.

About the concerns of backwards compatibility, it ensures it. You can continue using `ORG_RUNNER` without any issue. The only comment is that `RUNNER_SCOPE` is stronger.

Here you can find the behaviour for different cases:

<details><summary>Tests</summary>

```
WITH:
    GITHUB_HOST=my-host.com
    RUNNER_SCOPE=enterprise
    ENTERPRISE_NAME=my-enterprise
RESULT:
    RUNNER_SCOPE: enterprise
    _SHORT_URL: https://my-host.com/enterprises/my-enterprise
    _FULL_URL: https://my-host.com/api/v3/enterprises/my-enterprise/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    RUNNER_SCOPE=ent
    ENTERPRISE_NAME=my-enterprise
RESULT:
    RUNNER_SCOPE: enterprise
    _SHORT_URL: https://my-host.com/enterprises/my-enterprise
    _FULL_URL: https://my-host.com/api/v3/enterprises/my-enterprise/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    RUNNER_SCOPE=org
    ORG_NAME=my-org
RESULT:
    RUNNER_SCOPE: org
    _SHORT_URL: https://my-host.com/my-org
    _FULL_URL: https://my-host.com/api/v3/orgs/my-org/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    RUNNER_SCOPE=organisation
    ORG_NAME=my-org
RESULT:
    RUNNER_SCOPE: org
    _SHORT_URL: https://my-host.com/my-org
    _FULL_URL: https://my-host.com/api/v3/orgs/my-org/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    RUNNER_SCOPE=organization
    ORG_NAME=my-org
RESULT:
    RUNNER_SCOPE: org
    _SHORT_URL: https://my-host.com/my-org
    _FULL_URL: https://my-host.com/api/v3/orgs/my-org/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    RUNNER_SCOPE=repo
    REPO_URL=https://my-host.com/my_org/my_repo
RESULT:
    RUNNER_SCOPE: repo
    _SHORT_URL: https://my-host.com/my_org/my_repo
    _FULL_URL: https://my-host.com/api/v3/repos/my_org/my_repo/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    ORG_RUNNER=true
    ORG_NAME=my-org
RESULT:
    ORG_RUNNER: true
    RUNNER_SCOPE: org
    _SHORT_URL: https://git.my-host.com/my-org
    _FULL_URL: https://git.my-host.com/api/v3/orgs/my-org/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    ORG_NAME=my-org
    REPO_URL=https://my-host.com/my_org/my_repo
RESULT:
    RUNNER_SCOPE: repo
    _SHORT_URL: https://my-host.com/my_org/my_repo
    _FULL_URL: https://my-host.com/api/v3/repos/my_org/my_repo/actions/runners/registration-token

WITH:
    GITHUB_HOST=my-host.com
    RUNNER_SCOPE=repo
    ORG_RUNNER=true
    ORG_NAME=my-org
    REPO_URL=https://my-host.com/my_org/my_repo
RESULT:
    ORG_RUNNER: true
    RUNNER_SCOPE: repo
    _SHORT_URL: https://my-host.com/my_org/my_repo
    _FULL_URL: https://my-host.com/api/v3/repos/my_org/my_repo/actions/runners/registration-token
```

</details>

2021-06-03 14:24 UTC, myoung34 commented
Looks great!

You can remove the bits in the README about `ORG_RUNNER` and ill work a follow up PR to deprecate it

2021-06-03 14:25 UTC, myoung34 commented
Those tests are exactly what I was hoping for!

I'll merge it and modify the README so you can get this closed out

Just note: I don't backport releases, so this will be in `latest` only until upstream actions cuts a  new release which auto builds here

2021-06-03 14:25 UTC, myoung34 approved these changes

2021-06-03 14:26 UTC, merged

2021-06-05 10:04 UTC, jakubstefan commented
Thanks for the review :slightly_smiling_face: !