feat: Ephemeral mode
myoung34/docker-github-actions-runner pull request #140
Opened 2021-09-10 15:54 UTC by joeyparrish

This adds a script called ephemeral-runner.sh, which users can call as an explicit command to enable ephemeral mode.  It will register the runner with `--once`, and will terminate after a single job has been executed.

If the runner terminates with an exit code indicating that a software update has been installed (instead of running a job), then the script will wait for the update to complete and run itself again.

Combined with a service definition that restarts automatically, this allows for completely ephemeral operation of a self-hosted runner, in line with GitHub's own hosted runners.

2021-09-10 15:55 UTC, joeyparrish commented
If you like, I can add a template of the systemd service that I'm using to tie it all together.

2021-09-10 15:56 UTC, myoung34 commented
I think this is good. Can you add some documentation to README.md?

I assume youve tested this as working

2021-09-10 15:57 UTC, joeyparrish commented
Yes, I'm using it in production in a test lab for various projects my team owns.

2021-09-10 16:09 UTC, joeyparrish commented
I've pushed another commit that adds some documentation to README.md.  Let me know what you think.

2021-09-10 16:11 UTC, myoung34 requested changes

2021-09-10 16:11 UTC, myoung34 commented on README.md
> +GitHub's hosted runners are completely ephemeral.  You can `sudo rm -rf /` without breaking all future jobs.
```suggestion
GitHub's hosted runners are completely ephemeral.  You can remove all its data without breaking all future jobs.
```

I wouldnt want someone ever thinking `rm -rf /` is a good idea even in a container 😆

2021-09-10 16:11 UTC, myoung34 commented
One minor nuance and Im happy to merge

2021-09-10 16:16 UTC, joeyparrish commented
You make a good point.  :-)

2021-09-10 16:17 UTC, merged

2021-09-10 16:19 UTC, joeyparrish commented
Thanks!  Please let me know when I can start using the official image from Docker Hub again instead of my forked version.

2021-09-10 16:20 UTC, myoung34 commented
Itll finish [here](https://github.com/myoung34/docker-github-actions-runner/actions/runs/1221962268) 

Sid is failing but thats unrelated and I just need to find time to dig in

2021-09-11 01:23 UTC, JulianGro commented
> Sid is failing but thats unrelated and I just need to find time to dig in

I opened an issue in #142

2021-09-13 19:04 UTC, joeyparrish commented
Thanks!