Make sure there is no remnant runner config before configuring
myoung34/docker-github-actions-runner pull request #403
Opened 2024-10-05 07:25 UTC by bodograumann

Closes #402

2024-10-05 16:48 UTC, myoung34 requested changes
Also please add `[[ -f "/actions-runner/.runner" ]] && rm -f /actions-runner/.runner` to `deregister_runner()` after `./config.sh remove ...`

2024-10-05 16:48 UTC, myoung34 commented on entrypoint.sh
> +    # Make sure there is no remnant runner config, that would break registration
```suggestion
```

2024-10-05 16:48 UTC, myoung34 commented on entrypoint.sh
> +    # Cf. https://github.com/myoung34/docker-github-actions-runner/issues/402
```suggestion
```

no need for this breadcrumb, the commit will link to this PR

2024-10-05 16:48 UTC, myoung34 commented on entrypoint.sh
> +    rm -f /actions-runner/.runner
```suggestion
[[ -f "/actions-runner/.runner" ]] && rm -f /actions-runner/.runner
```

2024-10-05 18:09 UTC, bodograumann commented
Thanks for the quick response @myoung34 . I have incorporated your suggestions.

2024-10-06 19:06 UTC, myoung34 approved these changes

2024-10-06 19:06 UTC, merged